<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BooksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            // Arabic Books
            [
                'title' => 'قصائد من الشرق',
                'author' => 'نزار قباني',
                'genre' => 'Poetry',
                'publisher' => 'دار نزار قباني للنشر',
                'publication_date' => '1980-01-01',
                'price' => 9.99,
                'page_count' => 160,
                'description' => 'مجموعة شعرية تتناول الحب والسياسة والجمال.',
                'language' => 'AR',
                "image" => "test",
                "quantity" => 20
            ],
            [
                'title' => 'أيامي',
                'author' => 'طه حسين',
                'genre' => 'Biography',
                'publisher' => 'دار المعارف',
                'publication_date' => '1929-01-01',
                'price' => 14.99,
                'page_count' => 180,
                'description' => 'سيرة ذاتية للأديب المصري طه حسين تتناول طفولته وحياته الدراسية.',
                'language' => 'AR',
                "quantity" => 10,
                "image" => "test",
            ],
            [
                'title' => 'الرياضة وأهميتها في الحياة',
                'author' => 'عبد الفتاح صالح',
                'genre' => 'Sports',
                'publisher' => 'دار الفكر العربي',
                'publication_date' => '1995-01-01',
                'price' => 10.99,
                'page_count' => 220,
                'description' => 'يناقش الكتاب أهمية الرياضة في حياة الإنسان وفوائدها الصحية والنفسية.',
                'language' => 'AR',
                "image" => "test",
                "quantity" => 9
            ],
            [
                'title' => 'أساسيات التعليم',
                'author' => 'عبد الرحمن سالم',
                'genre' => 'Education',
                'publisher' => 'دار العلم للملايين',
                'publication_date' => '2003-01-01',
                'price' => 22.99,
                'page_count' => 340,
                'description' => 'كتاب يتناول أسس وطرق التعليم الفعالة في المدارس.',
                'language' => 'AR',
                "image" => "test",
                "quantity" => 7
            ],
            [
                'title' => 'الخط العربي: نشأته وتطوره',
                'author' => 'يوسف أحمد',
                'genre' => 'Art',
                'publisher' => 'دار النهضة العربية',
                'publication_date' => '1988-01-01',
                'price' => 17.99,
                'page_count' => 280,
                'description' => 'يتناول الكتاب تاريخ وتطور الخط العربي عبر العصور.',
                'language' => 'AR',
                "image" => "test",
                "quantity" => 19,
            ],
            [
                'title' => 'سرديات عربية',
                'author' => 'جبور الدويهي',
                'genre' => 'Fantasy',
                'publisher' => 'دار الساقي',
                'publication_date' => '2010-01-01',
                'price' => 12.99,
                'page_count' => 230,
                'description' => 'مجموعة من القصص القصيرة التي تمزج بين الخيال والواقع في المجتمع العربي.',
                'language' => 'AR',
                "image" => "test",
                "quantity" => 30
            ],
            [
                'title' => 'رحلة إلى بلاد الشام',
                'author' => 'ابن بطوطة',
                'genre' => 'Travel',
                'publisher' => 'دار الكتب العلمية',
                'publication_date' => '1355-01-01',
                'price' => 20.99,
                'page_count' => 350,
                'description' => 'رحلة الرحالة المغربي ابن بطوطة إلى بلاد الشام وما رآه من عادات وتقاليد.',
                'language' => 'AR',
                "image" => "test",
                "quantity" => 18
            ],
            [
                'title' => 'أعراس آمنة',
                'author' => 'إبراهيم نصر الله',
                'genre' => 'Poetry',
                'publisher' => 'المؤسسة العربية للدراسات والنشر',
                'publication_date' => '2004-01-01',
                'price' => 11.99,
                'page_count' => 190,
                'description' => 'مجموعة شعرية تتناول القضايا الاجتماعية والسياسية.',
                'language' => 'AR',
                "image" => "test",
                "quantity" => 42
            ],
            [
                'title' => 'العالم كما أراه',
                'author' => 'ألبرت أينشتاين (ترجمة: أحمد زكي)',
                'genre' => 'Biography',
                'publisher' => 'مكتبة الأسرة',
                'publication_date' => '1949-01-01',
                'price' => 13.99,
                'page_count' => 210,
                'description' => 'ترجمة عربية لمذكرات أينشتاين وآرائه في مختلف القضايا العلمية والاجتماعية.',
                'language' => 'AR',
                "image" => "test",
                "quantity" => 35
            ],
            [
                'title' => 'تاريخ العلوم عند العرب',
                'author' => 'جورج صليبا',
                'genre' => 'Science',
                'publisher' => 'دار العلم للملايين',
                'publication_date' => '1994-01-01',
                'price' => 24.99,
                'page_count' => 400,
                'description' => 'دراسة تاريخية لتطور العلوم في العالم العربي.',
                'language' => 'AR',
                "image" => "test",
                "quantity" => 25
            ],
            [
                'title' => 'فن الإدارة',
                'author' => 'جلال أمين',
                'genre' => 'Education',
                'publisher' => 'دار الشروق',
                'publication_date' => '2002-01-01',
                'price' => 16.99,
                'page_count' => 280,
                'description' => 'يناقش الكتاب أساسيات فن الإدارة وأساليبها الحديثة.',
                'language' => 'AR',
                "image" => "test",
                "quantity" => 22
            ],

            // spanish books

            [
                'title' => 'El Arte del Renacimiento',
                'author' => 'Luis Martín',
                'genre' => 'Art',
                'publisher' => 'Editorial Siglo XXI',
                'publication_date' => '2003-01-01',
                'price' => 25.99,
                'page_count' => 300,
                'description' => 'Un análisis del arte renacentista en Europa.',
                'language' => 'SP',
                "image" => "test",
                "quantity" => 31
            ],
            [
                'title' => 'La Fantasía del Futuro',
                'author' => 'Jorge Martínez',
                'genre' => 'Fantasy',
                'publisher' => 'Editorial Planeta',
                'publication_date' => '2010-01-01',
                'price' => 15.99,
                'page_count' => 220,
                'description' => 'Una novela de ciencia ficción que explora un futuro imaginario.',
                'language' => 'SP',
                "image" => "test",
                "quantity" => 41
            ],
            [
                'title' => 'Exploraciones por América Latina',
                'author' => 'Ana López',
                'genre' => 'Travel',
                'publisher' => 'Editorial Panorama',
                'publication_date' => '2015-01-01',
                'price' => 12.99,
                'page_count' => 350,
                'description' => 'Un libro sobre los viajes y aventuras en América Latina.',
                'language' => 'SP',
                "image" => "test",
                "quantity" => 16
            ],
            [
                'title' => 'Poesías de la Vida',
                'author' => 'Mario Vargas Llosa',
                'genre' => 'Poetry',
                'publisher' => 'Editorial Alfaguara',
                'publication_date' => '2008-01-01',
                'price' => 10.99,
                'page_count' => 180,
                'description' => 'Una colección de poemas sobre la vida y el amor.',
                'language' => 'SP',
                "image" => "test",
                "quantity" => 8
            ],
            [
                'title' => 'La Vida de un Hombre',
                'author' => 'Gabriel García Márquez',
                'genre' => 'Biography',
                'publisher' => 'Editorial Random House',
                'publication_date' => '1992-01-01',
                'price' => 14.99,
                'page_count' => 220,
                'description' => 'Una biografía detallada de la vida del famoso escritor colombiano.',
                'language' => 'SP',
                "image" => "test",
                "quantity" => 9
            ],
            [
                'title' => 'Teorías del Universo',
                'author' => 'Carlos Ruiz Zafón',
                'genre' => 'Science',
                'publisher' => 'Editorial Destino',
                'publication_date' => '2005-01-01',
                'price' => 21.99,
                'page_count' => 300,
                'description' => 'Un análisis de las teorías científicas del universo.',
                'language' => 'SP',
                "image" => "test",
                "quantity" => 15
            ],
            [
                'title' => 'El Deporte y la Salud',
                'author' => 'Fernando Alonso',
                'genre' => 'Sports',
                'publisher' => 'Editorial Planeta',
                'publication_date' => '2009-01-01',
                'price' => 18.99,
                'page_count' => 250,
                'description' => 'Un estudio sobre la relación entre deporte y salud.',
                'language' => 'SP',
                "image" => "test",
                "quantity" => 14
            ],
            [
                'title' => 'Educación y Aprendizaje',
                'author' => 'Isabel Allende',
                'genre' => 'Education',
                'publisher' => 'Editorial Norma',
                'publication_date' => '2013-01-01',
                'price' => 23.99,
                'page_count' => 320,
                'description' => 'Explora las metodologías modernas en el ámbito educativo.',
                'language' => 'SP',
                "image" => "test",
                "quantity" => 28
            ],
            [
                'title' => 'La Historia del Arte Moderno',
                'author' => 'Laura López',
                'genre' => 'Art',
                'publisher' => 'Editorial Anagrama',
                'publication_date' => '2000-01-01',
                'price' => 20.99,
                'page_count' => 290,
                'description' => 'Un recorrido por el arte moderno y sus influencias.',
                'language' => 'SP',
                "image" => "test",
                "quantity" => 11
            ],
            [
                'title' => 'Fantasía en la Realidad',
                'author' => 'Ricardo Piglia',
                'genre' => 'Fantasy',
                'publisher' => 'Editorial Galaxia Gutenberg',
                'publication_date' => '2011-01-01',
                'price' => 17.99,
                'page_count' => 230,
                'description' => 'Una novela que mezcla realidad y fantasía en un relato cautivador.',
                'language' => 'SP',
                "image" => "test",
                "quantity" => 12
            ],
            [
                'title' => 'Viaje por el Mediterráneo',
                'author' => 'Mario Benedetti',
                'genre' => 'Travel',
                'publisher' => 'Editorial Eterna Cadencia',
                'publication_date' => '2014-01-01',
                'price' => 16.99,
                'page_count' => 310,
                'description' => 'Relatos de un viaje fascinante por la región mediterránea.',
                'language' => 'SP',
                "image" => "test",
                "quantity" => 25
            ],
            [
                'title' => 'Rimas y Poemas',
                'author' => 'Luis Cernuda',
                'genre' => 'Poetry',
                'publisher' => 'Editorial Visor',
                'publication_date' => '1999-01-01',
                'price' => 12.99,
                'page_count' => 200,
                'description' => 'Colección de poemas que exploran el amor y la existencia.',
                'language' => 'SP',
                "image" => "test",
                "quantity" => 4
            ],
            [
                'title' => 'Historia de un Adolescente',
                'author' => 'Jorge Luis Borges',
                'genre' => 'Biography',
                'publisher' => 'Editorial Sudamericana',
                'publication_date' => '1997-01-01',
                'price' => 13.99,
                'page_count' => 190,
                'description' => 'Autobiografía de un adolescente en busca de su identidad.',
                'language' => 'SP',
                "image" => "test",
                "quantity" => 6
            ],
            [
                'title' => 'El Mundo de la Física Cuántica',
                'author' => 'Héctor García',
                'genre' => 'Science',
                'publisher' => 'Editorial Acantilado',
                'publication_date' => '2016-01-01',
                'price' => 28.99,
                'page_count' => 350,
                'description' => 'Una guía accesible sobre la física cuántica.',
                'language' => 'SP',
                "image" => "test",
                "quantity" => 8
            ],
            [
                'title' => 'Métodos de Enseñanza',
                'author' => 'Marta Rivas',
                'genre' => 'Education',
                'publisher' => 'Editorial Ediciones del Serbal',
                'publication_date' => '2018-01-01',
                'price' => 22.99,
                'page_count' => 270,
                'description' => 'Exploración de métodos y técnicas en la enseñanza moderna.',
                'language' => 'SP',
                "image" => "test",
                "quantity" => 30
            ],
            // French Books
            [
                'title' => 'L\'Art de la Renaissance',
                'author' => 'Pierre Dubois',
                'genre' => 'Art',
                'publisher' => 'Éditions Flammarion',
                'publication_date' => '2004-01-01',
                'price' => 23.99,
                'page_count' => 310,
                'description' => 'Une étude complète de l\'art de la Renaissance en Europe.',
                'language' => 'FR',
                "image" => "test",
                "quantity" => 30
            ],
            [
                'title' => 'Le Futur Fantastique',
                'author' => 'Jean-Paul Sartre',
                'genre' => 'Fantasy',
                'publisher' => 'Éditions Gallimard',
                'publication_date' => '2012-01-01',
                'price' => 18.99,
                'page_count' => 230,
                'description' => 'Un roman de science-fiction qui imagine un avenir incertain.',
                'language' => 'FR',
                "image" => "test",
                "quantity" => 28
            ],
            [
                'title' => 'Voyages en Afrique',
                'author' => 'Claude Lévi-Strauss',
                'genre' => 'Travel',
                'publisher' => 'Éditions Seuil',
                'publication_date' => '2008-01-01',
                'price' => 14.99,
                'page_count' => 340,
                'description' => 'Une exploration des cultures africaines à travers des récits de voyage.',
                'language' => 'FR',
                "image" => "test",
                "quantity" => 36
            ],
            [
                'title' => 'Poèmes d\'Amour',
                'author' => 'Paul Éluard',
                'genre' => 'Poetry',
                'publisher' => 'Éditions Poésie/Gallimard',
                'publication_date' => '1950-01-01',
                'price' => 11.99,
                'page_count' => 180,
                'description' => 'Une collection de poèmes d\'amour écrits par le célèbre poète français.',
                'language' => 'FR',
                "image" => "test",
                "quantity" => 46
            ],
            [
                'title' => 'La Vie d\'un Écrivain',
                'author' => 'Marcel Proust',
                'genre' => 'Biography',
                'publisher' => 'Éditions Gallimard',
                'publication_date' => '1980-01-01',
                'price' => 13.99,
                'page_count' => 210,
                'description' => 'Une biographie détaillée de l\'écrivain Marcel Proust.',
                'language' => 'FR',
                "image" => "test",
                "quantity" => 17
            ],
            [
                'title' => 'La Physique Quantique pour les Nuls',
                'author' => 'François Jacob',
                'genre' => 'Science',
                'publisher' => 'Éditions Eyrolles',
                'publication_date' => '2015-01-01',
                'price' => 27.99,
                'page_count' => 330,
                'description' => 'Une introduction accessible à la physique quantique.',
                'language' => 'FR',
                "image" => "test",
                "quantity" => 14
            ],
            [
                'title' => 'Le Sport et la Santé',
                'author' => 'Didier Deschamps',
                'genre' => 'Sports',
                'publisher' => 'Éditions Albin Michel',
                'publication_date' => '2012-01-01',
                'price' => 16.99,
                'page_count' => 260,
                'description' => 'Un guide complet sur l\'importance du sport pour la santé.',
                'language' => 'FR',
                "image" => "test",
                "quantity" => 15
            ],
            [
                'title' => 'L\'Éducation Moderne',
                'author' => 'Simone de Beauvoir',
                'genre' => 'Education',
                'publisher' => 'Éditions du Seuil',
                'publication_date' => '2018-01-01',
                'price' => 24.99,
                'page_count' => 300,
                'description' => 'Une exploration des méthodes éducatives modernes.',
                'language' => 'FR',
                "image" => "test",
                "quantity" => 14
            ],
            [
                'title' => 'L\'Art Contemporain',
                'author' => 'Yves Klein',
                'genre' => 'Art',
                'publisher' => 'Éditions Hazan',
                'publication_date' => '2006-01-01',
                'price' => 22.99,
                'page_count' => 280,
                'description' => 'Une analyse approfondie de l\'art contemporain.',
                'language' => 'FR',
                "image" => "test",
                "quantity" => 10
            ],
            [
                'title' => 'L\'Imaginaire dans la Littérature',
                'author' => 'Marguerite Yourcenar',
                'genre' => 'Fantasy',
                'publisher' => 'Éditions Verdier',
                'publication_date' => '2009-01-01',
                'price' => 20.99,
                'page_count' => 240,
                'description' => 'Un examen des éléments de fantaisie dans la littérature moderne.',
                'language' => 'FR',
                "image" => "test",
                "quantity" => 9
            ],
            [
                'title' => 'Voyages en Asie',
                'author' => 'Gérard de Nerval',
                'genre' => 'Travel',
                'publisher' => 'Éditions Arthaud',
                'publication_date' => '2004-01-01',
                'price' => 17.99,
                'page_count' => 310,
                'description' => 'Des récits de voyages fascinants à travers l\'Asie.',
                'language' => 'FR',
                "image" => "test",
                "quantity" => 10
            ],
            [
                'title' => 'Poèmes d\'Été',
                'author' => 'Arthur Rimbaud',
                'genre' => 'Poetry',
                'publisher' => 'Éditions Gallimard',
                'publication_date' => '1891-01-01',
                'price' => 13.99,
                'page_count' => 190,
                'description' => 'Une collection de poèmes célébrant la saison estivale.',
                'language' => 'FR',
                "image" => "test",
                "quantity" => 18
            ],
            [
                'title' => 'Le Voyage de la Vie',
                'author' => 'Albert Camus',
                'genre' => 'Biography',
                'publisher' => 'Éditions du Rocher',
                'publication_date' => '1965-01-01',
                'price' => 15.99,
                'page_count' => 200,
                'description' => 'Une biographie captivante d\'Albert Camus.',
                'language' => 'FR',
                "image" => "test",
                "quantity" => 21
            ],
            [
                'title' => 'La Découverte de l\'Univers',
                'author' => 'Henri Poincaré',
                'genre' => 'Science',
                'publisher' => 'Éditions Champs-Flammarion',
                'publication_date' => '1998-01-01',
                'price' => 25.99,
                'page_count' => 340,
                'description' => 'Une exploration des découvertes scientifiques concernant l\'univers.',
                'language' => 'FR',
                "image" => "test",
                "quantity" => 28
            ],
            [
                'title' => 'Méthodes d\'Enseignement Actuelles',
                'author' => 'Paul Ricoeur',
                'genre' => 'Education',
                'publisher' => 'Éditions Vrin',
                'publication_date' => '2017-01-01',
                'price' => 21.99,
                'page_count' => 270,
                'description' => 'Analyse des méthodes d\'enseignement en usage dans l\'éducation contemporaine.',
                'language' => 'FR',
                "image" => "test",
                "quantity" => 30
            ]
        ];
        DB::table('books')->insert($books);
}
}
